### PR TITLE
Fixing issure that happen all the time

### PR DESCRIPTION
**Pull request by FeelsBadMan1**
Hello, i made everything correct as it says in the description but if i choose manual captcha and any edumail site for register accounts my cmd will be spammed with this text: "Message: Unable to find a matching set of capabilities"
image

### CODE REVIEW

**Comment by 0m3rta13** [comment]
> Hello, i made everything correct as it says in the description but if i choose manual captcha and any edumail site for register accounts my cmd will be spammed with this text: "Message: Unable to find a matching set of capabilities"
> 
> image
> 
> 

Think you might've missed the more important part of the readme. 

_**I dont maintain the project anymore! Im planning to release a version WITHOUT selenium and requests only soon, so it will get way faster!**_

I also think that the college registration site has been redesigned since this script was last updated so I think the only way it's gonna be able to work I if it's pretty much rewritten from scratch.

**Comment by KevinLage** [comment]
I'll test the updated script later, if it works I'll merge it. Thanks for your work!

**Comment by KevinLage** [comment]
Tested it and it looks like only the account creator works but the application part doesn't. Anyone else who can confirm this?

**Comment by igosad** [comment]
not working .
`Message: invalid argument: can't kill an exited process

Message: invalid argument: can't kill an exited process

Message: invalid argument: can't kill an exited process

Message: invalid argument: can't kill an exited process

Message: invalid argument: can't kill an exited process

Message: invalid argument: can't kill an exited process

Message: invalid argument: can't kill an exited process`

**Pull request closed without merging**
