### PR TITLE
A lot of edits to improve the script.

### PR DESCRIPTION
**Pull request by sritub**

### CODE REVIEW

**Comment by sritub** [comment]
I used vscode and it seems to have automatically changed the formatting, sorry, please have a look in `def orange` for the WebDriverWait code I've added.

**Comment by KevinLage** [comment]
gonna test it later

**Comment by sritub** [comment]
I am testing before pushing, but sure.

**Comment by camlogical** [comment]
which temp mail still work with this bot?

**Comment by sritub** [comment]
> which temp mail still work with this bot?

This bot still uses tempr.email, I will try to add some other solution for colleges blocking tempr later.

**Comment by camlogical** [comment]
> > which temp mail still work with this bot?
> 
> This bot still uses tempr.email, I will try to add some other solution for colleges blocking tempr later.

Thank you. Can you add a function to sign in cccapply instead of create new account? because one cccapply account can register many colleges. I wish to have this function to easy register other colleges without starting from zero.

**Comment by sritub** [comment]
> > > which temp mail still work with this bot?
> > 
> > 
> > This bot still uses tempr.email, I will try to add some other solution for colleges blocking tempr later.
> 
> Thank you. Can you add a function to sign in cccapply instead of create new account? because one cccapply account can register many colleges. I wish to have this function to easy register other colleges without starting from zero.

Alright.

**Comment by KevinLage** [comment]
just use another domain from tempr.email

**Comment by camlogical** [comment]
> just use another domain from tempr.email

try many temp but no luck.

**Comment by sritub** [comment]
> > just use another domain from tempr.email
> 
> try many temp but no luck.

Try https://www.guerrillamail.com/

**Comment by sritub** [comment]
@camlogical I have updated the email domain, please try now, all colleges should be working. While logging in at tempr.email, please change the dropdown below the email input field to '@brunhilde.ml'.

**Comment by camlogical** [comment]
> @camlogical I have updated the email domain, please try now, all colleges should be working. While logging in at tempr.email, please change the dropdown below the email input field to '@brunhilde.ml'.

I will try. Are there any smarter ways to make this bot more good when college page update? for example #supplemental section, There are 2 radios but next month after college updated the radio increase to 3 or decrease to 1. this cause bot restart if it can't get element. Do you have any clue or we need to update it manually?

**Comment by sritub** [comment]
You can open an issue here then and we will update the bot :)

This is more of a script than a bot, it's not smart.

**Comment by KevinLage** [comment]
thanks

**Comment by UjjwalD77** [comment]
You know this project/Script  has a lot of potential .

**Comment by sritub** [comment]
@THEG77  Yeah, I'm currently working on a script that will generate protonvpn trial accounts, using this as inspiration. :)

**Pull request merged**
